### ISSUE TITLE
Make the "distance" matrix an input to the the GetSchedule service 

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#91]
To make the scheduler more portable I plan to make the matrix of durations of travel times between nodes an input to the GetSchedule service. I will remove DistWrapper from the scheduler and create DurationMatrix object which must be created before the Scheduler instance for the problem is created. @mudrole1 is this ok? Once I've done this then you will need to merge the changes into your own code, else we're probably going to the get too far out of sync.

**Comment by mudrole1** [comment]
I have done something pretty similar in my code all ready... the method getMaxDist() in scheduler.cpp computes the max distance (which is needed later to solve the issues when the task has no location). As it needs to determine all the pairs, Im saving them to the 2D array, which Im using later in the code and Im not asking Bruno's stuff again. So, I think the change in my code will be pretty straightforward.

**Comment by hawesie** [comment]
Yep, I saw that. Ok, I’ll make this change soon.=

**Comment by hawesie** [comment]
I'm looking at making the change, but I'm a bit confused with how you use `dist_a`. Should I understand `dist_a[i][j]` as the distance (duration of travel) between the end of task `i` and the start of task `j`?

**Comment by mudrole1** [comment]
i,j are just indexes referring to the order of tasks in set. So that tasksToS->at(i) will give you one task. This uses the fact that the order of tasks in the set doesnt change during one scheduling. However, as Im thinking about it now, we might want to do it in different way - your way, to use task, or its ID to refer in the array. (this will be useful when rescheduling, that still the same DurationMatrix object)
